### ISSUE TITLE
 save age as date of birth

### ISSUE THREAD

**Issue by mb666** [Wryczak/family#8]
to be defined: requirement

**Comment by Wryczak** [comment]
Back-end: 
changing field in class Member -from age/ to date of birth(String value)
add a method that counts the period between the date of birth and the present day
Creating MemberDTO - (adding extra fields like : age - parsed from birthdate to age.

Front: Changing of assumed values from numeric to date (calendar)
Remove  age input (age will be calculated with date of birth)

**Comment by Wryczak** [comment]
Member field -age -changed to date of birth (Date type).
One method added to  calculate age.
MemberDTO - use this calculator to count age, and show it.

**Comment by mb666** [comment]
w tym commicie byla ta zmiana 570ffc6ad364506d12c6926f44560121fddcd961
